config/routes.rb
Rails.application.routes.draw do
  #Se define el renombramiento de los controladores y acciones
  get "index", to: "inicio#index"
  get 'students/:student_id/index', to: 'students#index', as: :student_index
  get 'students/:student_id/schedules/index', to: 'schedules#index', as: :student_schedule

  get 'students/:student_id/monitorings/ver', to: 'monitorings#ver', as: :ver_student_monitoring
  get 'students/:student_id/monitorings/inscribir', to: 'monitorings#inscribir', as: :inscribir_student_monitoring
  post 'students/:student_id/monitorings/inscribir', to: 'monitorings#inscribir', as: :inscribir_student_monitoring_post
  get 'students/:student_id/monitorings/index', to: 'monitorings#index'
  get 'students/:student_id/monitorings/contracts', to: 'monitorings#contracts', as: :contract_student_monitoring

  post 'academics/students/:student_id/schedules', to: 'academics/students/schedules#index', as: :schedule_materias_academics
  get 'academics/students/:student_id/schedules/historial', to: 'academics/students/schedules#historial', as: :historial_schedule_student
  post 'academics/students/:student_id/schedules/historial', to: 'academics/students/schedules#chistorial', as: :create_historial_schedule_student

  get 'academics/groups/index', as: :academic_group
  get 'academics/schedules/index', as: :academic_schedule
  get 'academics/students/index', to: 'academics/students#index', as: :academic_student
  post 'academics/students/new', to: 'academics/students#create'
  get 'academics/students/schedules/index', to: 'academics/students/schedules#index'
  post 'academics/groups/new', to: 'academics/groups#create'

  post 'academics/subjects/new', to: 'academics/subjects#create'
  get 'teachers/index'


  get 'registers/', to: 'registers#index'
  get 'registers/students/:student_id/notes', to: 'registers/students/notes#index'
  get 'registers/students/:student_id/notes/:note_id/edit', to: 'registers/students/notes#edit'
  get 'registers/students/:student_id/notes/new', to: 'registers/students/notes#new'
  #get 'registers/students/:student_id', to: 'registers/students#show'
  delete 'registers/students/:student_id/notes/:note_id', to: 'registers/students/notes#destroy', as: :destroy_note_student_registers
  post 'registers/students/:student_id/notes/new', to: 'registers/students/notes#create', as: :new_registers_student_note
  post 'registers/students/:student_id/notes/:note_id/edit', to: 'registers/students/notes#update', as: :update_registers_student_note
  devise_for :students, controllers: {
    registrations: 'students/registrations',
    sessions: 'students/sessions'}

  devise_scope :student do
    authenticate :student do
      #root 'students#index', as: :authenticate_student_root
    end

    authenticated :student do
      #RUTA PARA USUARIOS QUE YA INICIARON SESION
      #root 'students#index', as: :authenticated_student_root
    end

    unauthenticated :student do
      #RUTA PARA USUARIOS QUE NO HAN INICIADO SESION
      #root 'students/sessions#new', as: :unauthenticated_student_root
      #root 'inicio#index', as: :unauthenticated_student_root
    end
  end


  devise_for :teachers, controllers: {
    registrations: 'teachers/registrations',
    sessions: 'teachers/sessions'}

  #GET - SE PUEDE ACCEDER DESDE LAS RUTAS DESDE LA BARRA DE DIRECCIONES
  #POST - EL MAS SEGURO. SOLO SE PUEDE ACCEDER A TRAVES DE LINKS Y ACCIONES DE LA WEB


  #Definicio de recursos 

  resources :teachers
  
  resources :students do
    resources :schedules
    resources :monitorings
  end
  
  resources :resources do
    resources :teachers
  end

  #CURSOS, HORARIOS, SALONES, MATRICULAS
  namespace :academics do
    resources :subjects
    resources :students do
      scope module: :students do 
        resources :schedules
      end
    end
    resources :groups
  end
  resources :academics
  
  namespace :registers do
    resources :students do
      scope module: :students do
        resources :notes
      end
    end
  end
  resources :registers

  #deinifion de la ruta de arranque del servidor web
  root 'inicio#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/models/group.rb
class Group < ApplicationRecord


    #self.primary_key = "codigo", "subject"
	belongs_to :subject
	#OPTIONAL ASEGURA QUE NO SEA ENCESARIO PASAR LA REFERENCIA, QUE ESTA SE NULA
	belongs_to :teacher, optional: true 

	has_and_belongs_to_many :schedules
	has_and_belongs_to_many :students
	has_many :notes

	def self.toArray
		arr = Array.new
		groups = Group.all
		groups.each do |group|
			subject = group.subject.nombre
			arr.push(group.id.to_s + "-" + group.codigo.to_s + "-" + subject)
		end
		return arr
	end
end

app/controllers/academics/groups_controller.rb
class Academics::GroupsController < ApplicationController
	layout 'teachers'
	def index
		@groups = Group.all
	end
	def show 
	    #ENCONTRAR REGISTRO POR EL ID
	  	@group = Group.find(params[:id])
	end

	def new
  		@group = Group.new
  		@groups = Group.all
  	end

	def create
		id_subject = params[:group][:subject_id].split("-").at(0).to_i
		id_teacher = params[:group][:teacher_id].split("-").at(0).to_i
		@group = Group.new(group_params)
		@group.teacher_id = id_teacher
		@group.subject_id = id_subject
	    if @group.save
	    	puts 'Registrado'
	      redirect_to academic_group_path(@group)
	    else
	      puts @group.errors.inspect
	      render :new
	    end
	end

	def update
		id_subject = params[:group][:subject_id].split("-").at(0).to_i
		id_teacher = params[:group][:teacher_id].split("-").at(0).to_i
	    @group = Group.find(params[:id])
	    if @group.update(group_params)
	      redirect_to @group
	    else
	      render :new
		end
	end

	def edit
		@group = Group.find(params[:id])
	end

	private

	def group_params
		params.require(:group).permit(:codigo)
	end
end

app/controllers/academics/students/schedules_controller.rb
class Academics::Students::SchedulesController < ApplicationController
	layout 'teachers'

	def historial
		@logs = Student.find(params[:student_id]).logs

	end

	def chistorial
		student = Student.find(params[:student_id])
		codigo_materia = params[:codigo_materia].to_s.split("-").at(0)
		promedio_carrera = params[:promedio_carrera]
		nota_materia = params[:nota_materia]

		if promedio_carrera != ""
			student.promedio_carrera = promedio_carrera	
		end
		if codigo_materia != "" and nota_materia != ""
			student.logs.create(subject_id: codigo_materia.to_i, semester_id: student.semesters.last.id.to_i, nota_final: nota_materia.to_f)
		else
			return
		end
		
		if student.save
			redirect_to historial_schedule_student_path
		else
			puts student.errors.inspect
		end
	end
end

app/controllers/academics/students_controller.rb
class Academics::StudentsController < ApplicationController
	layout 'teachers'
	def index
		if !teacher_signed_in?
			redirect_to new_teacher_session_path
		end
		@students = Student.all
	end

	def show
		@student = Student.find(params[:id])
	end

	def new
		@student = Student.new
	end

	def create
		program = params[:student][:programa]
		sem = params[:student][:semesters]
		@student = Student.new(student_params)

		programs = Program.where(nombre: program.split("-").at(1))
		semester = Semester.find(sem)
		@student.semesters << semester
		programs.each do |program|
			@student.programa = program.id
			@student.matricula = program.matricula.to_f
		end
		
		if @student.save
			StudentMailer.new_student(student).deliver_now
			redirect_to @student
		else
			puts @student.errors.inspect
			render :new
		end
	end

	def update
        program = params[:student][:programa]
	    sem = params[:student][:semesters]
	    @student = Student.find(params[:id])

	    programs = Program.where(nombre: program.split("-").at(1))
	    semester = Semester.find(sem)
	    @student.semesters << semester
	    programs.each do |program|
	      @student.programa = program.id
	      @student.matricula = program.matricula.to_f
	    end
    
	    if @student.update(student_params)
	      redirect_to @student.id
	    else
	      render :new
		end
	end

	def edit
		@student = Student.find(params[:id])
	end

	def new
		@student = Student.new
	end

	private

	  def student_params
	    params.require(:student).permit(:email, :password, :password_confirmation, :nombres, :apellidos, :codigo, :documento, :es_egresado)
	  end
end

app/controllers/academics/subjects_controller.rb
class Academics::SubjectsController < ApplicationController
	layout 'teachers'

	def index
		@subjects = Subject.all
	end
	def show
		@subjects = Subject.all
		@subject = Subject.find(params[:id])
	end

	def new
		@subjects = Subject.all
		@subject = Subject.new
	end

	def create
		semestre = params[:subject][:semester_id].split("-").at(0)
		@subject = Subject.new(subject_params)
		@subject.semester_id = semestre
		if @subject.save
			redirect_to academics_subjects_path
		else
			puts @subject.errors.inspect
			render :new
		end
	end

	def edit
		@subject = Subject.find(params[:id])
	end

	def update
		semestre = params[:subject][:semester_id].split("-").at(0)
		@subject = Subject.new(subject_params)
		@subject.semester_id = semester_id
		if @subject.save
			redirect_to academics_subjects_path
		else
			puts @subject.errors.inspect
			render :new
		end
	end

	def subject_params
  	params.require(:subject).permit(:codigo, :nombre, :creditos, :semester_id)
  end

end

app/controllers/academics_controller.rb
class AcademicsController < ApplicationController
	layout 'teachers'
	def index
		@notifications = Notification.all.where(solucionado: 0)
	end
end

app/helpers/academics/groups_helper.rb
module Academics::GroupsHelper
end

app/helpers/academics/students/schedules_helper.rb
module Academics::Students::SchedulesHelper
end

app/helpers/academics/students_helper.rb
module Academics::StudentsHelper
end

app/helpers/academics/subjects_helper.rb
module Academics::SubjectsHelper
end

app/helpers/academics_helper.rb
module AcademicsHelper
end

app/views/academics/groups/_form.html.erb
<%= form_for @group, url: new_academics_group_path, method: :post, html: { id: "LayoutContentGHrupos" } do |f| %>
    <div class="row">
        <div class="col-1">
            

            <hr id="LineSeparatorGroupAcademic">
            <div id="wb_TextEditGrupo">
                <span style="color:#808080;"><strong><%= title %> Grupo</strong></span>
            </div>

            <%= f.text_field :codigo, placeholder: "Codigo del grupo", class: "EditBox", value: "", type: "number", id: "EditboxCodigoGrupoAcademic"%>

            <hr id="LineSeparatorGroupAcademic2">

            <%= f.select :subject_id, Subject.cargarMaterias,{ prompt: "Seleccione la materia"}, id: "ComboboxSubjectGroupAcademic" %>

            <hr id="LineGroupAcademic2">

            <%= f.select :teacher_id, Teacher.cargarProfesores,{ prompt: "Seleccione la materia"}, id: "ComboboxTeacherGroupAcademic" %>

            <hr id="LineGroupAcademic3">

            <div id="wb_ButtonRegistrarGroupAcademic">
                <%= f.submit "Registrar", id: "ButtonRegistrarGroupAcademic", class: "boton", style: "color: #FFFFFF"%> 
            </div>

            <hr id="LineGroupAcademic5">
        </div>
    </div>
<% end %>

app/views/academics/groups/_infogroups.html.erb
<div id="wb_TextGestionGrupoAcademic">
    <span style="color:#808080;"><strong>Gestion de Grupos</strong></span>
</div>
<table id="TableGruposAcademic">
    <tr>
        <td class="cell0"><span style="color:#333333;font-family:'Segoe UI';font-size:24px;line-height:32px;"><strong>ID</strong></span></td>
        <td class="cell0"><span style="color:#333333;font-family:'Segoe UI';font-size:24px;line-height:32px;"><strong>Codigo</strong></span></td>
        <td class="cell0"><span style="color:#333333;font-family:'Segoe UI';font-size:24px;line-height:32px;"><strong>Materia</strong></span></td>
        <td class="cell0"><span style="color:#333333;font-family:'Segoe UI';font-size:24px;line-height:32px;"><strong>Profesor</strong></span></td>
        <td class="cell0"><span style="color:#333333;font-family:'Segoe UI';font-size:24px;line-height:32px;"><strong>Editar</strong></span></td>
    </tr>
    <% @groups.each do |group| %>
        <tr>
            <td class="cell0"><span style="color:#333333;font-family:'Segoe UI';font-size:14px;line-height:32px;"><%=group.id %></span></td>
            <td class="cell0"><span style="color:#333333;font-family:'Segoe UI';font-size:14px;line-height:32px;"><%=group.codigo %></span></td>
            <td class="cell0"><span style="color:#333333;font-family:'Segoe UI';font-size:14px;line-height:32px;">
                    <% if group.subject_id != nil %>
                        <%=Subject.obtenerMateriaPorID(group.subject_id) %>
                    <% else %>
                        <%="Sin Materia" %>
                    <% end %>    
                </span>
            </td>
            <td class="cell0"><span style="color:#333333;font-family:'Segoe UI';font-size:14px;line-height:32px;">
                    <% if group.teacher_id != nil %>
                        <%=Teacher.obtenerNombresPorID(group.teacher_id) %>
                    <% else %>
                        <%="Sin profesor" %>
                    <% end %>  
                </span></td>
            <td class="cell0"><span style="color:#333333;font-family:'Segoe UI';font-size:14px;line-height:32px;">
                    <%=link_to "Editar", controller: "groups", action: "edit", id: group.id.to_s %>
                </span>
            </td>
        </tr>  
    <% end %>
    
</table>

app/views/academics/groups/edit.html.erb
<div id="wb_LayoutGridGruposAcademic">
    <div id="LayoutGridGruposAcademic">
        <div class="row">
            <div class="col-1">
                <div id="wb_LayoutContentGHrupos">
					<%= render "form", title: "Editar" %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/academics/groups/index.html.erb
<div id="wb_LayoutGridGruposAcademic">
    <div id="LayoutGridGruposAcademic">
        <div class="row">
            <div class="col-1">
                <div id="wb_LayoutContentGHrupos">
                	<%= render "infogroups" %>
                	<div id="wb_ButtonRegistrarGroupAcademic" style= "padding-top: 15px; padding-bottom: 15px;">
                        <a class="ui-button ui-widget ui-corner-all" id="ButtonRegistrarGroupAcademic" href=<%= "/academics/groups/new" %> target="_self" title="Agregar Grupo" id="ButtonRegistrarGroupAcademic" class="boton">Añadir un Grupo</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/academics/groups/new.html.erb
<div id="wb_LayoutGridGruposAcademic">
    <div id="LayoutGridGruposAcademic">
        <div class="row">
            <div class="col-1">
                <div id="wb_LayoutContentGHrupos">
                    <%= render "infogroups"%>
                    <%= render "form", title: "Crear" %>
                </div>
            </div>
        </div>
    </div>
</div>