config/routes.rb
Rails.application.routes.draw do
  #Se define el renombramiento de los controladores y acciones
  get "index", to: "inicio#index"
  get 'students/:student_id/index', to: 'students#index', as: :student_index
  get 'students/:student_id/schedules/index', to: 'schedules#index', as: :student_schedule

  get 'students/:student_id/monitorings/ver', to: 'monitorings#ver', as: :ver_student_monitoring
  get 'students/:student_id/monitorings/inscribir', to: 'monitorings#inscribir', as: :inscribir_student_monitoring
  post 'students/:student_id/monitorings/inscribir', to: 'monitorings#inscribir', as: :inscribir_student_monitoring_post
  get 'students/:student_id/monitorings/index', to: 'monitorings#index'
  get 'students/:student_id/monitorings/contracts', to: 'monitorings#contracts', as: :contract_student_monitoring

  post 'academics/students/:student_id/schedules', to: 'academics/students/schedules#index', as: :schedule_materias_academics
  get 'academics/students/:student_id/schedules/historial', to: 'academics/students/schedules#historial', as: :historial_schedule_student
  post 'academics/students/:student_id/schedules/historial', to: 'academics/students/schedules#chistorial', as: :create_historial_schedule_student

  get 'academics/groups/index', as: :academic_group
  get 'academics/schedules/index', as: :academic_schedule
  get 'academics/students/index', to: 'academics/students#index', as: :academic_student
  post 'academics/students/new', to: 'academics/students#create'
  get 'academics/students/schedules/index', to: 'academics/students/schedules#index'
  post 'academics/groups/new', to: 'academics/groups#create'

  post 'academics/subjects/new', to: 'academics/subjects#create'
  get 'teachers/index'


  get 'registers/', to: 'registers#index'
  get 'registers/students/:student_id/notes', to: 'registers/students/notes#index'
  get 'registers/students/:student_id/notes/:note_id/edit', to: 'registers/students/notes#edit'
  get 'registers/students/:student_id/notes/new', to: 'registers/students/notes#new'
  #get 'registers/students/:student_id', to: 'registers/students#show'
  delete 'registers/students/:student_id/notes/:note_id', to: 'registers/students/notes#destroy', as: :destroy_note_student_registers
  post 'registers/students/:student_id/notes/new', to: 'registers/students/notes#create', as: :new_registers_student_note
  post 'registers/students/:student_id/notes/:note_id/edit', to: 'registers/students/notes#update', as: :update_registers_student_note
  devise_for :students, controllers: {
    registrations: 'students/registrations',
    sessions: 'students/sessions'}

  devise_scope :student do
    authenticate :student do
      #root 'students#index', as: :authenticate_student_root
    end

    authenticated :student do
      #RUTA PARA USUARIOS QUE YA INICIARON SESION
      #root 'students#index', as: :authenticated_student_root
    end

    unauthenticated :student do
      #RUTA PARA USUARIOS QUE NO HAN INICIADO SESION
      #root 'students/sessions#new', as: :unauthenticated_student_root
      #root 'inicio#index', as: :unauthenticated_student_root
    end
  end


  devise_for :teachers, controllers: {
    registrations: 'teachers/registrations',
    sessions: 'teachers/sessions'}

  #GET - SE PUEDE ACCEDER DESDE LAS RUTAS DESDE LA BARRA DE DIRECCIONES
  #POST - EL MAS SEGURO. SOLO SE PUEDE ACCEDER A TRAVES DE LINKS Y ACCIONES DE LA WEB


  #Definicio de recursos 

  resources :teachers
  
  resources :students do
    resources :schedules
    resources :monitorings
  end
  
  resources :resources do
    resources :teachers
  end

  #CURSOS, HORARIOS, SALONES, MATRICULAS
  namespace :academics do
    resources :subjects
    resources :students do
      scope module: :students do 
        resources :schedules
      end
    end
    resources :groups
  end
  resources :academics
  
  namespace :registers do
    resources :students do
      scope module: :students do
        resources :notes
      end
    end
  end
  resources :registers

  #deinifion de la ruta de arranque del servidor web
  root 'inicio#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/controllers/monitorings_controller.rb
class MonitoringsController < ApplicationController
	layout 'students'
	def initialize
		super
		@mensajes = Array.new
	end
	def index
		redirect_to ver_student_monitoring_path(current_student)
	end

	def ver
		#@groups = Group.joins(:subject).where.not(student_id: nil)
		@subjects = Subject.where(student_id: nil)
		@student = Student.find(params[:student_id])
	end 

	def contracts
		@esMonitor = Student.verificarEstudiante(params[:student_id])

		@program = Student.obtenerCarrera(params[:student_id])
		@school = Student.obtenerFacultad(params[:student_id])
		@pago = Student.calcularDescuentoMatricula(params[:student_id])

		Notification.crearNotificacion("Contrato", "Generar Contrato", "/students/" + params[:student_id].to_s + "monitorings#contracts", 1, params[:student_id].to_i)
	end

	def inscribir
		@student = Student.find(params[:student_id])
		puts params[:codigo_materia]
		grupoDisponible = Student.buscarMateriaDisponible(params[:student_id],params[:codigo_materia].to_i)
		vioMateria = Student.vioCurso(params[:student_id], params[:codigo_materia].to_i)
		cumplePromedio = Student.calcPromedio(params[:student_id])
		creditos = Student.calc_credits(params[:student_id])
		estSinMonitoria = Student.verificarEstudiante(params[:student_id])

		@mensaje = Array.new
		@todoBien = true
		if !grupoDisponible
			@todoBien = false
			@mensaje.push("El grupo ya tiene monitor disponible.")
			puts "El grupo ya tiene monitor disponible."
		end
		if !vioMateria
			@todoBien = false
			@mensaje.push("El estudiante no ha visto la materia aun")
			puts "El estudiante no ha visto la materia aun"
		end
		if !cumplePromedio
			@todoBien = false
			@mensaje.push("El estudiante no cumple el promedio requerido ser monitor")
			puts "El estudiante no cumple el promedio requerido ser monitor"
		end
		if creditos < 22
			@todoBien = false
			@mensaje.push("El estudiante no cumple con los minimos creditos vistos.")
			puts "El estudiante no cumple con los minimos creditos vistos."
		end

		if !estSinMonitoria
			@todoBien = false
			@mensaje.push("El estudiante ya tiene una materia como monitor, no puede inscribirse en mas materias")
			puts "El estudiante ya tiene una materia como monitor, no puede inscribirse en mas materias"
		end

		if @todoBien
			@mensaje.push(Student.ingresarMonitoria(params[:student_id], params[:codigo_materia].to_i))
			puts @mensaje
			if Student.descontarMatricula(params[:student_id])
				@mensaje.push("Se ha descontado " + @pago.to_s + " a la matricula.")
				@mensaje.push("Nuevo pago de matricula: " + current_student.matricula.to_s)
			else
				@mensaje.push("No se pudo descontar la matricula, contactese con la Universidad para mas informacion")
				url = "students"
				Notification.crearNotificacion("Descuento", "Inscribirse a Monitoria", "/students/" + params[:student_id].to_s + "monitorings#inscribir", 0, params[:student_id].to_i)
			end
		else
			Notification.crearNotificacion("Inscripcion", "Inscribirse a Monitoria", "/students/" + params[:student_id].to_s + "monitorings#inscribir", 0, params[:student_id].to_i)
		end
	end
end

app/helpers/monitorings_helper.rb
module MonitoringsHelper
end

app/helpers/students/monitoring_helper.rb
module Students::MonitoringHelper
end

app/views/monitorings/_inscripcion.html.erb
<div id="wb_LayoutGrid3">
    <div id="LayoutGrid3">
        <div class="row">
            <div class="col-1">
                <hr id="Line1InsMonMen">
                <div id="wb_TextAdvertenciaInsMom">
                    <span style="color:#4F4F4F;font-family:'Segoe UI';font-size:16px;">
                        <% if !todoBien %>
                            <strong><%= "No se pudo asignar el estudiante a la materia. Razon:"%></strong><br>
                        <%end%>
                        <% if mensaje != nil %>

                            <%mensaje.each do |m|%>
                                *<%= m%><br>
                            <%end%> 
                        <%else%>
                            <%puts 'mensaje es nulo'%>
                        <%end%> 
                    </span>
                </div>
            </div>
        </div>
    </div>
</div>
<div id="wb_LayoutFormInsMon">
    <form name="Confirmacion" method="post" action="../index.html" enctype="text/plain" id="LayoutFormInsMon">
        <div class="row">
            <div class="col-1">
                <hr id="LineFinalInsMonMen">
            </div>
        </div>
    </form>
</div>

app/views/monitorings/index.html.erb
<% if student_signed_in? %>
    <script type="text/javascript">
        window.location.href=<%=  %>  // put your correct path in a string here
    </script>
<% else %>
    <script type="text/javascript">
        window.location.href="/students/sign_in"  // put your correct path in a string here
    </script>
<% end %>

app/views/monitorings/inscribir.html.erb
<div id="wb_LayoutContenidoInsMon">
    <div id="LayoutContenidoInsMon">
        <div class="row">
            <div class="col-1">
                <%= render "/students/infoest", student: @student %>
            </div>
        </div>
    </div>
</div>
<div id="wb_LayoutGrid7">
    <div id="LayoutGrid7">
        <div class="row">
            <div class="col-1">
                <hr id="LineFinalInsMon">
            </div>
        </div>
    </div>
</div>
<div id="wb_LayoutContentFormInsMo">
    <div id="LayoutContentFormInsMo">
        <div class="row">
            <div class="col-1">
                <div id="wb_LayoutFormInsMat">

                    <%= form_tag(inscribir_student_monitoring_post_path) do%>
                        <%= text_field_tag 'codigo_materia', nil, placeholder: "Codigo de la materia", class: "EditBox", id: "EditboxCodigoMatInsMat"%>
                        <hr id="LinSepComForm">
                        
                        <div id="wb_ButtonInsMatInsMat">
                            <%= submit_tag "Inscribirse", id: "ButtonInsMatInsMat", class: "boton", style: "color: #FFFFFF"%> 
                        </div>
                    <% end %>
                    <%= render "inscripcion", mensaje: @mensaje, todoBien: @todoBien%>
                </div>
            </div>
        </div>
    </div>
</div>
<div id="wb_LayoutGridSep">
    <div id="LayoutGridSep">
        <div class="row">
            <div class="col-1">
                <hr id="LineSepInsmAT">
            </div>
        </div>
    </div>
</div>

app/views/monitorings/ver.html.erb
<div id="wb_LayoutGridInfoUserVerMon">
    <%= render "/students/infoest", student: @student %>
</div>
<div id="wb_LayoutGridSepVerMon">
    <div id="LayoutGridSepVerMon">
        <div class="row">
            <div class="col-1">
                <hr id="Line2VerMon">
            </div>
        </div>
    </div>
</div>

<div id="wb_LayoutContenidoVerMon">
    <form name="matricula" method="post" action="" enctype="text/plain" accept-charset="UTF-8" id="LayoutContenidoVerMon">
        <div class="row">
            <div class="col-1">
                <hr id="LineVerMon">
                <div id="wb_Text1" class="TextoNoticia">
                    <span style="color:#000000;font-family:Arial;font-size:13px;">Se muestran a continuacion las materias que aun no tienen monitor asignado. El estudiante puede inscribirse a solo una materia. Una vez inscrito, la materia no estara disponible para que otro estudiante escoja esta.</span>
                </div>
                <hr id="Line1">
                <table id="TablaMateriasVerMon">
                    <tr>
                        <td class="cell0">
                            <span style="color:#000000;">
                                <strong>CODIGO</strong>
                            </span>
                        </td>
                        <td class="cell0">
                            <span style="color:#000000;">
                                <strong>MATERIA</strong>
                            </span>
                        </td>
                        <td class="cell0">
                            <span style="color:#000000;">
                                <strong>CREDITOS</strong>
                            </span>
                        </td>
                    </tr>
                    <!--<td class="cell1">
                            IMPRESION DEL CODIGO DEL GRUPO
                            <span style="color:#000000;">g.codigo</span>
                        </td>
                        <td class="cell2">
                            IMPRESION DEL CODIGO DE LA MATERIA
                            <span style="color:#000000;">g.subject.codigo</span>
                        </td>
                        <td class="cell2">
                            <span style="color:#000000;">g.subject.nombre</span>
                        </td>
                        <td class="cell2">
                            <span style="color:#000000;">g.subject.creditos</span>
                        </td>-->
                    <%= @subjects.each do |g| %>
                        <tr>
                            <td class="cell2">
                                <span style="color:#000000;"><%= g.codigo%></span>
                            </td>
                            <td class="cell2">
                                <span style="color:#000000;"><%= g.nombre%></span>
                            </td>
                            <td class="cell2">
                                <span style="color:#000000;"><%= g.creditos%></span>
                            </td>
                        </tr>   
                    <% end %>

                    
                    
                </table>
                <hr id="Line8">
            </div>
        </div>
    </form>
</div>