config/routes.rb
Rails.application.routes.draw do
  #Se define el renombramiento de los controladores y acciones
  get "index", to: "inicio#index"
  get 'students/:student_id/index', to: 'students#index', as: :student_index
  get 'students/:student_id/schedules/index', to: 'schedules#index', as: :student_schedule

  get 'students/:student_id/monitorings/ver', to: 'monitorings#ver', as: :ver_student_monitoring
  get 'students/:student_id/monitorings/inscribir', to: 'monitorings#inscribir', as: :inscribir_student_monitoring
  post 'students/:student_id/monitorings/inscribir', to: 'monitorings#inscribir', as: :inscribir_student_monitoring_post
  get 'students/:student_id/monitorings/index', to: 'monitorings#index'
  get 'students/:student_id/monitorings/contracts', to: 'monitorings#contracts', as: :contract_student_monitoring

  post 'academics/students/:student_id/schedules', to: 'academics/students/schedules#index', as: :schedule_materias_academics
  get 'academics/students/:student_id/schedules/historial', to: 'academics/students/schedules#historial', as: :historial_schedule_student
  post 'academics/students/:student_id/schedules/historial', to: 'academics/students/schedules#chistorial', as: :create_historial_schedule_student

  get 'academics/groups/index', as: :academic_group
  get 'academics/schedules/index', as: :academic_schedule
  get 'academics/students/index', to: 'academics/students#index', as: :academic_student
  post 'academics/students/new', to: 'academics/students#create'
  get 'academics/students/schedules/index', to: 'academics/students/schedules#index'
  post 'academics/groups/new', to: 'academics/groups#create'

  post 'academics/subjects/new', to: 'academics/subjects#create'
  get 'teachers/index'


  get 'registers/', to: 'registers#index'
  get 'registers/students/:student_id/notes', to: 'registers/students/notes#index'
  get 'registers/students/:student_id/notes/:note_id/edit', to: 'registers/students/notes#edit'
  get 'registers/students/:student_id/notes/new', to: 'registers/students/notes#new'
  #get 'registers/students/:student_id', to: 'registers/students#show'
  delete 'registers/students/:student_id/notes/:note_id', to: 'registers/students/notes#destroy', as: :destroy_note_student_registers
  post 'registers/students/:student_id/notes/new', to: 'registers/students/notes#create', as: :new_registers_student_note
  post 'registers/students/:student_id/notes/:note_id/edit', to: 'registers/students/notes#update', as: :update_registers_student_note
  devise_for :students, controllers: {
    registrations: 'students/registrations',
    sessions: 'students/sessions'}

  devise_scope :student do
    authenticate :student do
      #root 'students#index', as: :authenticate_student_root
    end

    authenticated :student do
      #RUTA PARA USUARIOS QUE YA INICIARON SESION
      #root 'students#index', as: :authenticated_student_root
    end

    unauthenticated :student do
      #RUTA PARA USUARIOS QUE NO HAN INICIADO SESION
      #root 'students/sessions#new', as: :unauthenticated_student_root
      #root 'inicio#index', as: :unauthenticated_student_root
    end
  end


  devise_for :teachers, controllers: {
    registrations: 'teachers/registrations',
    sessions: 'teachers/sessions'}

  #GET - SE PUEDE ACCEDER DESDE LAS RUTAS DESDE LA BARRA DE DIRECCIONES
  #POST - EL MAS SEGURO. SOLO SE PUEDE ACCEDER A TRAVES DE LINKS Y ACCIONES DE LA WEB


  #Definicio de recursos 

  resources :teachers
  
  resources :students do
    resources :schedules
    resources :monitorings
  end
  
  resources :resources do
    resources :teachers
  end

  #CURSOS, HORARIOS, SALONES, MATRICULAS
  namespace :academics do
    resources :subjects
    resources :students do
      scope module: :students do 
        resources :schedules
      end
    end
    resources :groups
  end
  resources :academics
  
  namespace :registers do
    resources :students do
      scope module: :students do
        resources :notes
      end
    end
  end
  resources :registers

  #deinifion de la ruta de arranque del servidor web
  root 'inicio#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/models/note.rb
class Note < ApplicationRecord
  #self.primary_key = "group", "student", "subject"

  belongs_to :student
  belongs_to :group
  belongs_to :subject
end

app/controllers/academics/students/schedules_controller.rb
class Academics::Students::SchedulesController < ApplicationController
	layout 'teachers'

	def historial
		@logs = Student.find(params[:student_id]).logs

	end

	def chistorial
		student = Student.find(params[:student_id])
		codigo_materia = params[:codigo_materia].to_s.split("-").at(0)
		promedio_carrera = params[:promedio_carrera]
		nota_materia = params[:nota_materia]

		if promedio_carrera != ""
			student.promedio_carrera = promedio_carrera	
		end
		if codigo_materia != "" and nota_materia != ""
			student.logs.create(subject_id: codigo_materia.to_i, semester_id: student.semesters.last.id.to_i, nota_final: nota_materia.to_f)
		else
			return
		end
		
		if student.save
			redirect_to historial_schedule_student_path
		else
			puts student.errors.inspect
		end
	end
end

app/controllers/academics/students_controller.rb
class Academics::StudentsController < ApplicationController
	layout 'teachers'
	def index
		if !teacher_signed_in?
			redirect_to new_teacher_session_path
		end
		@students = Student.all
	end

	def show
		@student = Student.find(params[:id])
	end

	def new
		@student = Student.new
	end

	def create
		program = params[:student][:programa]
		sem = params[:student][:semesters]
		@student = Student.new(student_params)

		programs = Program.where(nombre: program.split("-").at(1))
		semester = Semester.find(sem)
		@student.semesters << semester
		programs.each do |program|
			@student.programa = program.id
			@student.matricula = program.matricula.to_f
		end
		
		if @student.save
			StudentMailer.new_student(student).deliver_now
			redirect_to @student
		else
			puts @student.errors.inspect
			render :new
		end
	end

	def update
        program = params[:student][:programa]
	    sem = params[:student][:semesters]
	    @student = Student.find(params[:id])

	    programs = Program.where(nombre: program.split("-").at(1))
	    semester = Semester.find(sem)
	    @student.semesters << semester
	    programs.each do |program|
	      @student.programa = program.id
	      @student.matricula = program.matricula.to_f
	    end
    
	    if @student.update(student_params)
	      redirect_to @student.id
	    else
	      render :new
		end
	end

	def edit
		@student = Student.find(params[:id])
	end

	def new
		@student = Student.new
	end

	private

	  def student_params
	    params.require(:student).permit(:email, :password, :password_confirmation, :nombres, :apellidos, :codigo, :documento, :es_egresado)
	  end
end

app/controllers/registers/students/notes_controller.rb
class Registers::Students::NotesController < ApplicationController
	layout 'teachers'
	def index
		@id_student = params[:student_id]
		@notes = Student.find(@id_student).notes
	end

	def edit
		@note = Note.find(params[:note_id])
	end

	def new
		@note = Note.new

	end

	def create
		@group_id = params[:note][:group_id].split("-").at(0).to_i
		@subject_id = params[:note][:subject_id].split("-").at(0).to_i
		@student_id = params[:student_id].to_i
		subject_name = Group.find(@group_id).subject.nombre
		subject = Subject.find(@subject_id).nombre
		if subject_name == subject
			@student = Student.find(@student_id)
			@note = @student.notes.new(note_params)
			@note.subject_id = @subject_id
			@note.group_id = @group_id
			if @note.save
				redirect_to registers_student_notes_path
			else
				puts @note.errors.inspect
				render :new
			end
		else
			puts 'La materia escogida no esta en el grupo seleccionado'
		end

	end

	def edit
		@note = Student.find(params[:student_id]).notes.find(params[:note_id])
	end

	def update

		@group_id = params[:note][:group_id].split("-").at(0).to_i
		@subject_id = params[:note][:subject_id].split("-").at(0).to_i
		@student_id = params[:student_id].to_i
		subject_name = Group.find(@group_id).subject.nombre
		subject = Subject.find(@subject_id).nombre
		if subject_name == subject
			@student = Student.find(@student_id)
			@note = @student.notes.find(params[:note_id])
			@note.subject_id = @subject_id
			@note.group_id = @group_id
			if @note.update(note_params)
				redirect_to registers_student_notes_path
			else
				puts @note.errors.inspect
				render :new
			end
		else
			puts 'La materia escogida no esta en el grupo seleccionado'
		end
	end

	def destroy
		@note = Student.find(params[:student_id]).notes.find(params[:note_id])
		@note.destroy
		redirect_to registers_student_notes_path
	end

	private

	def note_params
		params.require(:note).permit(:nota)
	end
end

app/controllers/registers/students/students_controller.rb
class Registers::Students::StudentsController < ApplicationController
	layout 'teachers'

	def show
		@students = Student.all
		@student = Student.find(params[:id])
		@esMonitor = Student.verificarEstudiante(params[:id])
		@program = Student.obtenerCarrera(params[:id])
		@school = Student.obtenerFacultad(params[:id])
		@pago = Student.calcularDescuentoMatricula(params[:id])
		@monitor = Student.esMonitor(params[:id])
	end
end

app/controllers/students/confirmations_controller.rb
# frozen_string_literal: true

class Students::ConfirmationsController < Devise::ConfirmationsController
  layout 'students'
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/students/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Students::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  layout 'students'
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/students/passwords_controller.rb
# frozen_string_literal: true

class Students::PasswordsController < Devise::PasswordsController
  layout 'students'
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/students/registrations_controller.rb
# frozen_string_literal: true

class Students::RegistrationsController < Devise::RegistrationsController
  layout 'students'
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end
  
  #POST /resource
  def create
    program = params[:student][:programa]
    sem = params[:student][:semesters]
    @student = Student.new(student_params)

    programs = Program.where(nombre: program.split("-").at(1))
    semester = Semester.find(sem)
    @student.semesters << semester
    programs.each do |program|
      @student.programa = program.id
      @student.matricula = program.matricula.to_f
    end
    
    if @student.save
      redirect_to @student
    else
      puts @student.errors.inspect
      render :new
    end
  end

def edit
  @student = Student.find(params[:id])
end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  private

  def student_params
    params.require(:student).permit(:email, :password, :password_confirmation, :nombres, :apellidos, :codigo, :documento, :es_egresado)
  end
end

app/controllers/students/sessions_controller.rb
# frozen_string_literal: true

class Students::SessionsController < Devise::SessionsController
  layout 'students'
  #
  #skip_before_filter :verify_authenticity_token
  before_action :configure_permitted_parameters, if: :devise_controller?
  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_in) do |user_params|
      user_params.permit(:codigo, :password)
    end
  end
  def after_sign_in_path_for(resource)
    request.env['omniauth.origin'] || stored_location_for(resource) || students_path
  end
  def after_sign_out_path_for(resource_or_scope)
    new_student_session_path
  end 

end

app/controllers/students/unlocks_controller.rb
# frozen_string_literal: true

class Students::UnlocksController < Devise::UnlocksController
  layout 'students'
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/academics/students/schedules_helper.rb
module Academics::Students::SchedulesHelper
end

app/helpers/academics/students_helper.rb
module Academics::StudentsHelper
end

app/helpers/registers/notes_helper.rb
module Registers::NotesHelper
end

app/helpers/registers/students_helper.rb
module Registers::StudentsHelper
end

app/helpers/registros/students_helper.rb
module Registros::StudentsHelper
end

app/helpers/students/monitoring_helper.rb
module Students::MonitoringHelper
end

app/helpers/students/schedules_helper.rb
module Students::SchedulesHelper
end

app/views/registers/students/notes/_form.html.erb
<div id="wb_LayoutGridNotaAddContainer">
    <div id="LayoutGridNotaAddContainer">
        <div class="row">
            <div class="col-1">
                <div id="wb_LayoutContentNotaAdd">
                    <div id="LayoutContentNotaAdd">
                        <div class="row">
                            <div class="col-1">
                                <div id="wb_TextAddNotasTitle">
                                    <span style="color:#808080;"><strong><%= operacion + " una nota"%></strong></span>
                                </div>
                                <hr id="LineSeparatorNotasAdd1">

                                    <%= form_for @note, url: new_registers_student_note_path, method: :post do |f| %>

                                    <% if editar %>
                                        
                                        <div id="wb_TextInfoNotas">
                                            <span style="color:#696969;font-family:'Segoe UI';font-size:16px;">INFORMACION NOTAS...…...</span>
                                        </div>
                                    <% end %>
                                    <%= f.select :group_id, Group.toArray,{ prompt: "Selecciona el grupo"}, id: "ComboboxGrupoNota" %>

                                    <hr id="LineSeparatorNotasAdd3">

                                    <%= f.select :subject_id, Subject.obtenerMaterias,{ prompt: "Selecciona la materia"}, id: "ComboboxMateriaNota" %>

                                    <hr id="LineSeparatorNotasAdd4">

                                    <%= f.text_field :nota, placeholder: "Nota (Decimal)", class: "EditBox", value: "", type: "number", id: "EditboxNotaNumNota", min:'0', step: '0.01'%>

                                    <div id="wb_ButtonRegistrarNota", style="padding-top: 15px;">
                                        <%= f.submit "Registrar", id: "ButtonRegistrarNota", class: "boton", style: "color: #FFFFFF;"%> 
                                    </div>
                                    <hr id="LineSeparatorNotasAdd6">
                                    
                                <% end %>
                                <% if editar %>
                                    <%= form_tag(destroy_note_student_registers_path(:note_id)) do%>
                                        <div id="wb_ButtonEliminarNota", style="padding-top: 15px;">
                                            <%= submit_tag "Eliminar", id: "ButtonEliminarNota", class: "boton", style: "color: #FFFFFF;"%> 
                                        </div>
                                    <% end %>
                                <% end %>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/registers/students/notes/edit.html.erb
<% if teacher_signed_in? %>
    <% if current_teacher.especialidad == "Administrador" %>
    	<div id="wb_LayoutGridNotaAddContainer">
		    <div id="LayoutGridNotaAddContainer">
		        <div class="row">
		            <div class="col-1">
		                <div id="wb_LayoutContentNotaAdd">
		                    <div id="LayoutContentNotaAdd">
		                        <div class="row">
		                            <div class="col-1">
		                                <div id="wb_TextAddNotasTitle">
		                                    <span style="color:#808080;"><strong>Editar una nota</strong></span>
		                                </div>
		                                <hr id="LineSeparatorNotasAdd1">
		                                    <%= form_for @note, url: update_registers_student_note_path(student_id: params[:student_id], note_id: params[:note_id]), method: :post do |f| %>
		                                        
	                                        <div id="wb_TextInfoNotas">
	                                            <span style="color:#696969;font-family:'Segoe UI';font-size:16px;">INFORMACION NOTAS...…...</span>
	                                        </div>

	                                        <hr id="LineSeparatorNotasAdd2">

		                                    <%= f.select :group_id, Group.toArray,{ prompt: "Selecciona el grupo"}, id: "ComboboxGrupoNota" %>

		                                    <hr id="LineSeparatorNotasAdd3">

		                                    <%= f.select :subject_id, Subject.obtenerMaterias,{ prompt: "Selecciona la materia"}, id: "ComboboxMateriaNota" %>

		                                    <hr id="LineSeparatorNotasAdd4">

		                                    <%= f.text_field :nota, placeholder: "Nota (Decimal)", class: "EditBox", value: "", type: "number", id: "EditboxNotaNumNota", min:'0', step: '0.01'%>

		                                    <div id="wb_ButtonRegistrarNota", style="padding-top: 15px;">
		                                        <%= f.submit "Registrar", id: "ButtonRegistrarNota", class: "boton", style: "color: #FFFFFF;"%> 
		                                    </div>
		                                    <hr id="LineSeparatorNotasAdd6">
		                                    
		                                <% end %>
	                                    <%= form_tag(destroy_note_student_registers_path(:note_id)) do%>
	                                        <div id="wb_ButtonEliminarNota", style="padding-top: 15px;">
	                                            <%= submit_tag "Eliminar", id: "ButtonEliminarNota", class: "boton", style: "color: #FFFFFF;"%> 
	                                        </div>
	                                	<% end %>
		                            </div>
		                        </div>
		                    </div>
		                </div>
		            </div>
		        </div>
		    </div>
		</div>
    <% end %>
<% else %>
    <h1>El sitio web no ha podido ser encontrado</h1>
<% end %>

app/views/registers/students/notes/index.html.erb
<% if teacher_signed_in? %>
    <% if current_teacher.especialidad == "Administrador" %>
        <div id="wb_LayoutGridGestionNotas">
            <div id="LayoutGridGestionNotas">
                <div class="row">
                    <div class="col-1">
                        <div id="wb_LayoutContentGestionNotas">
                            <div id="LayoutContentGestionNotas">
                                <div class="row">
                                    <div class="col-1">
                                        <div id="wb_TextGestionNotas">
                                            <span style="color:#808080;"><strong>Gestion de Notas</strong></span>
                                        </div>
                                        <hr id="LineSeparatorNotasGestion">
                                        <table id="TableNotasGestionNotas">
                                            <tr>
                                                <td class="cell0"><span style="color:#333333;font-family:'Segoe UI';font-size:24px;line-height:32px;"><strong>Codigo de la materia</strong></span></td>
                                                <td class="cell0"><span style="color:#333333;font-family:'Segoe UI';font-size:24px;line-height:32px;"><strong>Nombre de la materia</strong></span></td>
                                                <td class="cell0"><span style="color:#333333;font-family:'Segoe UI';font-size:24px;line-height:32px;"><strong>Nota</strong></span></td>
                                                <td class="cell0"><span style="color:#333333;font-family:'Segoe UI';font-size:24px;line-height:32px;"><strong>Editar</strong></span></td>
                                            </tr>
                                            <% @notes.each do |note| %>
                                                <% subjects = Subject.obtenerInfoMateria(note.subject_id) %>
                                                <tr>
                                                    <td class="cell0"><span style="color:#333333;font-family:'Segoe UI';font-size:18px;line-height:32px;"><%= subjects.at(0).to_s %></span></td>
                                                    <td class="cell0"><span style="color:#333333;font-family:'Segoe UI';font-size:18px;line-height:32px;"><%= subjects.at(1) %></span></td>
                                                    <td class="cell0"><span style="color:#333333;font-family:'Segoe UI';font-size:18px;line-height:32px;"><%= note.nota.to_s %></span></td>
                                                    <td class="cell0"><span style="color:#333333;font-family:'Segoe UI';font-size:18px;line-height:32px;"><a href=<%= "/registers/students/" + @id_student.to_s + "/notes/" + note.id.to_s + "/edit"%>>Editar</a></span></td>
                                                </tr>
                                            <%end%>
                                        </table>
                                        <div id="wb_ButtonRegistrarGroupAcademic" style= "padding-top: 15px; padding-bottom: 15px;">
                                            <a class="ui-button ui-widget ui-corner-all" id="ButtonRegistrarGroupAcademic" href=<%= "/registers/students/" + @id_student + "/notes/new" %> target="_self" title="Agregar Estudiante" id="ButtonRegistrarGroupAcademic" class="boton">Añadir Nota</a>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <% end %>
<% else %>
    <h1>El sitio web no ha podido ser encontrado</h1>
<% end %>

app/views/registers/students/notes/new.html.erb
<%= render 'form', editar: false, operacion: "Crear" %>